apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: redmine
  labels:
    app: redmine
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  source:
    type: Git
    git:
      uri: https://github.com/asubee/openshift-lesson.git
  output:
    to:
      kind: ImageStreamTag
      name: 'redmine:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: redmine/redmine/Dockerfile
      from:
        kind: DockerImage
        name: 'redmine:5.1'
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange

