version: '2'

# redmine with postgres

services:
  postgres:
    image: postgres
    volumes:
      - redmine-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: redmine
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: redmine

  redmine:
    build:
      context: ../build/
      dockerfile: Dockerfile
    volumes:
      - redmine-files:/usr/redmine/files
    ports:
      - "3000:3000"
    links:
      - postgres
    restart: always
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: postgres
      REDMINE_DB_DATABASE: redmine

volumes:
  redmine-db:
    external: true
  redmine-files:
    external: true
