apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app: redmine
spec:
  accessModes:
    - ReadWriteOnce #単一ノードからRead/Writeが可能。
  resources:
    requests:
      storage: 20Gi

